# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.0.4"

  config.vm.define "node" do |node|
    # Box Settings
    node.vm.box = "bento/ubuntu-16.04"
    node.vm.hostname = "node"

    # Provider Settings
    node.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      vb.name = "node"
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end
    node.vm.network "private_network", ip: "192.168.11.100"
    node.vm.provision "shell", path: "provision/bootstrap.sh", privileged: false
    #node.vm.provision "shell", path: "provision/bootstrap-node.sh", privileged: false
  end

end